/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Article = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
});
export const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });

export const idlService = IDL.Service({
  'addArticle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addFAQ' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getArticlesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'submitConsultation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Article = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
  });
  const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  
  return IDL.Service({
    'addArticle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addFAQ' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'submitConsultation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };